const axios = require('axios');

module.exports = {
    command: ['imagine', 'generate', 'aiimage', 'dalle'],
    description: 'Generate images using AI',
    example: '.imagine a beautiful sunset over mountains',
    tags: ['ai'],

    handler: async (conn, m) => {
        try {
            const prompt = m.text;
            
            if (!prompt) {
                return m.reply('❌ Please provide a description for the image!\n\n📝 Example: `.imagine a beautiful sunset over mountains`');
            }

            if (prompt.length < 5) {
                return m.reply('❌ Please provide a more detailed description (at least 5 characters)!');
            }

            await m.reply('🎨 AI is generating your image... This may take a moment.');

            const apiKey = global.config.apiKeys.openai;
            
            try {
                if (apiKey) {
                    // Use OpenAI DALL-E API if available
                    const response = await axios.post('https://api.openai.com/v1/images/generations', {
                        prompt: prompt,
                        n: 1,
                        size: '1024x1024',
                        response_format: 'url'
                    }, {
                        headers: {
                            'Authorization': `Bearer ${apiKey}`,
                            'Content-Type': 'application/json'
                        },
                        timeout: 60000 // 60 seconds for image generation
                    });

                    if (response.data.data && response.data.data[0]) {
                        const imageUrl = response.data.data[0].url;
                        
                        // Download the generated image
                        const imageResponse = await axios.get(imageUrl, { 
                            responseType: 'arraybuffer',
                            timeout: 30000 
                        });
                        const imageBuffer = Buffer.from(imageResponse.data);
                        
                        const caption = `🎨 *AI Generated Image*\n\n` +
                            `📝 *Prompt:* ${prompt}\n` +
                            `🤖 *Generated by:* DALL-E\n` +
                            `⏰ *Generated at:* ${new Date().toLocaleString()}`;
                        
                        await m.sendImage(imageBuffer, caption);
                    } else {
                        throw new Error('No image generated');
                    }
                } else {
                    // Fallback: Provide alternative services
                    const fallbackText = `🎨 *AI Image Generation*\n\n` +
                        `📝 *Your prompt:* ${prompt}\n\n` +
                        `❌ *AI image generation requires an API key.*\n\n` +
                        `🌐 *Alternative services you can try:*\n` +
                        `• DALL-E 2: https://openai.com/dall-e-2/\n` +
                        `• Midjourney: https://www.midjourney.com/\n` +
                        `• Stable Diffusion: https://stability.ai/\n` +
                        `• Bing Image Creator: https://www.bing.com/create\n` +
                        `• Leonardo AI: https://leonardo.ai/\n\n` +
                        `💡 *Tip:* Copy your prompt and paste it in any of these services!`;
                    
                    await m.reply(fallbackText);
                }

            } catch (error) {
                console.error('AI Image API error:', error);
                
                let errorMessage = '❌ Failed to generate image! ';
                
                if (error.response?.status === 400) {
                    errorMessage += 'The prompt might contain inappropriate content or be too long.';
                } else if (error.response?.status === 429) {
                    errorMessage += 'Too many requests. Please try again later.';
                } else if (error.response?.status === 401) {
                    errorMessage += 'API authentication failed. Please contact the bot owner.';
                } else {
                    errorMessage += 'Please try again later or use alternative AI image services.';
                }
                
                errorMessage += '\n\n🌐 *Alternative services:*\n';
                errorMessage += '• DALL-E 2: https://openai.com/dall-e-2/\n';
                errorMessage += '• Bing Image Creator: https://www.bing.com/create\n';
                errorMessage += '• Leonardo AI: https://leonardo.ai/';
                
                await m.reply(errorMessage);
            }

        } catch (error) {
            console.error('Error in imagine command:', error);
            await m.reply('❌ Error processing image generation request!');
        }
    }
};
